jwt:
  config:
    key: cwq
    ttl: 36000
spring:   datasource:
    url: jdbc:mysql://localhost:3306/yun?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 960879872chenwq
    driver-class-name: com.mysql.cj.jdbc.Driver