spring: 
  application:  
    name: tensquare-search #指定服务名
  datasource:
    url: jdbc:mysql://localhost:3306/tensquare_base?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 960879872chenwq
    #driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
     host: 192.168.41.131  # mq的ip
server:
  port: 8081
  